;;; emacs-jupyter-notebook-lifecycle-stress.el --- AG3 Gate 3 -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'emacs-jupyter-notebook-stress)
(require 'emacs-jupyter-notebook-helper)

(defconst ejn-ag3-lifecycle--fixture
  (expand-file-name "tests/stress/fixtures/ag3_lifecycle_helper.py"
                    ejn-ag3--root))

(defun ejn-ag3-lifecycle--slots-clear-p (session)
  (and (emacs-jupyter-notebook-helper-session-disposed session)
       (null (emacs-jupyter-notebook-helper-session-process session))
       (null (emacs-jupyter-notebook-helper-session-stderr-process session))
       (null (emacs-jupyter-notebook-helper-session-stderr-buffer session))
       (null (emacs-jupyter-notebook-helper-session-decoder session))
       (null (emacs-jupyter-notebook-helper-session-owner-buffer session))
       (null (emacs-jupyter-notebook-helper-session-hello-timer session))
       (null (emacs-jupyter-notebook-helper-session-partial-timer session))
       (null (emacs-jupyter-notebook-helper-session-decode-timer session))
       (null (emacs-jupyter-notebook-helper-session-drain-timer session))
       (null (emacs-jupyter-notebook-helper-session-stderr-drain-timer session))
       (null (emacs-jupyter-notebook-helper-session-startup-exit-timer session))
       (null (emacs-jupyter-notebook-helper-session-ping-timer session))
       (null (emacs-jupyter-notebook-helper-session-ping-id session))
       (null (emacs-jupyter-notebook-helper-session-control-timer session))
       (or (null (emacs-jupyter-notebook-helper-session-requests session))
           (and (hash-table-p (emacs-jupyter-notebook-helper-session-requests session))
                (= (hash-table-count (emacs-jupyter-notebook-helper-session-requests session)) 0)))
       (null (emacs-jupyter-notebook-helper-session-event-queue session))
       (null (emacs-jupyter-notebook-helper-session-event-tail session))
       (null (emacs-jupyter-notebook-helper-session-priority-queue session))
       (null (emacs-jupyter-notebook-helper-session-priority-tail session))
       (null (emacs-jupyter-notebook-helper-session-raw-chunks session))
       (null (emacs-jupyter-notebook-helper-session-raw-tail session))
       (= (emacs-jupyter-notebook-helper-session-raw-bytes session) 0)
       (or (null (emacs-jupyter-notebook-helper-session-event-queue-bytes session))
           (= (emacs-jupyter-notebook-helper-session-event-queue-bytes session) 0))
       (or (null (emacs-jupyter-notebook-helper-session-priority-queue-bytes session))
           (= (emacs-jupyter-notebook-helper-session-priority-queue-bytes session) 0))
       (not (memq session emacs-jupyter-notebook-helper--sessions))))

(defun ejn-ag3-lifecycle--run (phase timing)
  (let* ((owner (generate-new-buffer " *ejn-ag3-lifecycle-owner*"))
         (ready-count 0) (failure-count 0) (closed-count 0)
         (request-count 0) (request-response nil) (request-error nil) session
         (ticks 0) canary
         (started (float-time))
         (command (list (or (executable-find "python3") "python3")
                        ejn-ag3-lifecycle--fixture phase timing)))
    (unwind-protect
        (progn
          (setq canary (run-at-time 0 0.05 (lambda () (cl-incf ticks))))
          (setq session
                (let ((emacs-jupyter-notebook-helper-command command)
                      (emacs-jupyter-notebook-helper-hello-timeout 0.3)
                      (emacs-jupyter-notebook-helper-partial-frame-timeout 0.15)
                      (emacs-jupyter-notebook-helper--ping-interval 300))
                  (emacs-jupyter-notebook-helper-start
                   :buffer owner
                   :ready-callback (lambda (&rest _) (cl-incf ready-count))
                   :closed-callback (lambda (&rest _) (cl-incf closed-count))
                   :failure-callback (lambda (_ reason) (cl-incf failure-count)
                                       (setq request-error reason)))))
          (when (member phase '("connect" "execute" "close" "ping"))
            (should (ejn-ag3--await (lambda () (> ready-count 0)) 1))
            (emacs-jupyter-notebook-helper-request
             session phase (make-hash-table :test 'equal)
             (lambda (_ response error)
               (cl-incf request-count)
               (setq request-response response request-error error))
             :timeout 0.4))
          (let ((deadline (+ (float-time) 2.0)))
            (while (and (not (emacs-jupyter-notebook-helper-session-disposed session))
                        (< (float-time) deadline))
              (accept-process-output nil 0.01)))
          (should (emacs-jupyter-notebook-helper-session-disposed session))
          (should (= failure-count 1))
          (should (= closed-count 1))
          (should (= request-count (if (member phase '("connect" "execute" "close" "ping")) 1 0)))
          (if (and (member phase '("connect" "execute" "close" "ping"))
                   (equal timing "post"))
              (should request-response)
            (when (member phase '("connect" "execute" "close" "ping"))
              (should request-error)))
          (when (equal phase "hello")
            (should (= ready-count (if (equal timing "post") 1 0))))
          (when (equal phase "grant_event_credit") (should (= ready-count 1)))
          (when (equal phase "ready-idle") (should (= ready-count 1)))
          (let ((wall (- (float-time) started)))
            (should (>= ticks (max 1 (floor (/ wall 0.1)))))
            (ejn-ag3--metric (format "th1-lifecycle-%s-%s" phase timing)
                             (cons "wall" wall)
                             (cons "canary_ticks" ticks)
                             (cons "failure_callbacks" failure-count)
                             (cons "closed_callbacks" closed-count)
                             (cons "request_callbacks" request-count)
                             (cons "ready_callbacks" ready-count)))
          (should (ejn-ag3-lifecycle--slots-clear-p session))
          (should-not
           (cl-find-if (lambda (buffer)
                         (string-match-p "\\` \\*ejn-helper-stderr-" (buffer-name buffer)))
                       (buffer-list))))
      (when session (emacs-jupyter-notebook-helper-dispose session "lifecycle cleanup"))
      (when (timerp canary) (cancel-timer canary))
      (when (buffer-live-p owner) (kill-buffer owner))
      (ejn-ag3--kill-helpers))))

(ert-deftest ejn-ag3-lifecycle-helper-exits-at-every-phase ()
  (setq ejn-ag3--started-at (float-time))
  (dolist (case '("hello" "grant_event_credit"))
    (ejn-ag3-lifecycle--run case "pre")
    (ejn-ag3-lifecycle--run case "post"))
  (ejn-ag3-lifecycle--run "ready-idle" "post")
  (dolist (case '("ping" "connect" "execute" "close"))
    (ejn-ag3-lifecycle--run case "pre")
    (ejn-ag3-lifecycle--run case "post")))

(ert-deftest ejn-ag3-lifecycle-late-ping-response-is-bounded ()
  (setq ejn-ag3--started-at (float-time))
  (let* ((owner (generate-new-buffer " *ejn-ag3-late-owner*"))
         session ready callbacks callback-error callback-response
         (ticks 0) (started (float-time)) canary)
    (unwind-protect
        (progn
          (setq canary (run-at-time 0 0.05 (lambda () (cl-incf ticks))))
          (let ((emacs-jupyter-notebook-helper-command
                 (list (or (executable-find "python3") "python3")
                       ejn-ag3-lifecycle--fixture "late-ping" "post" "--late-delay" "0.5"))
                (emacs-jupyter-notebook-helper-hello-timeout 0.3)
                (emacs-jupyter-notebook-helper--ping-interval 300))
            (setq session (emacs-jupyter-notebook-helper-start
                           :buffer owner :ready-callback (lambda (&rest _) (setq ready t)))))
          (should (ejn-ag3--await (lambda () ready) 1))
          (emacs-jupyter-notebook-helper-request
           session "ping" (make-hash-table :test 'equal)
           (lambda (_ response error)
             (setq callbacks (1+ (or callbacks 0))
                   callback-error error
                   callback-response response))
           :timeout 0.1)
          (should (ejn-ag3--await (lambda () (and callbacks (= callbacks 1))) 1))
          (ejn-ag3--drain-for 0.7)
          (should (= callbacks 1))
          (should-not callback-response)
          (should (string-match-p "timed out" callback-error))
          (should (= (length
                      (emacs-jupyter-notebook-helper-session-late-responses session))
                     1))
          (let ((wall (- (float-time) started)))
            (should (>= ticks (max 1 (floor (/ wall 0.1))))))
          (emacs-jupyter-notebook-helper-dispose session "late response cleanup")
          (should (ejn-ag3-lifecycle--slots-clear-p session))
          (ejn-ag3--metric "th1-lifecycle-late-ping"
                           (cons "callbacks" callbacks)
                           (cons "late_responses" 1)
                           (cons "canary_ticks" ticks)))
      (when session (emacs-jupyter-notebook-helper-dispose session "late cleanup"))
      (when (timerp canary) (cancel-timer canary))
      (when (buffer-live-p owner) (kill-buffer owner))
      (ejn-ag3--kill-helpers))))

(provide 'emacs-jupyter-notebook-lifecycle-stress)
