;;; emacs-jupyter-notebook-heartbeat-setup-tests.el --- Setup liveness regressions -*- lexical-binding: t; -*-

;;; Commentary:
;; Silent startup work owns the kernel shell without a user execution record.
;; Heartbeat silence during that work cannot establish transport failure.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'emacs-jupyter-notebook)

(ert-deftest ejn-heartbeat-setup-suspends-probes-and-retires-prior-timeout ()
  "A pending setup sequence closes the otherwise idle heartbeat gate."
  (with-temp-buffer
    (let ((emacs-jupyter-notebook--client 'test-client)
          (emacs-jupyter-notebook--execution-setup-pending t)
          (emacs-jupyter-notebook--execution-active-id nil)
          (emacs-jupyter-notebook--kernel-status nil)
          (emacs-jupyter-notebook--tunnel-dead nil)
          (emacs-jupyter-notebook--heartbeat-misses 1)
          (timeout (run-at-time 600 nil #'ignore))
          sent)
      (unwind-protect
          (cl-letf (((symbol-function 'emacs-jupyter-notebook-backend-aux)
                     (lambda (&rest _) (setq sent t))))
            (setq emacs-jupyter-notebook--heartbeat-timeout-timer timeout
                  emacs-jupyter-notebook--heartbeat-inflight 'prior-probe)
            (emacs-jupyter-notebook--heartbeat-tick)
            (should-not sent)
            (should-not emacs-jupyter-notebook--heartbeat-inflight)
            (should-not emacs-jupyter-notebook--heartbeat-timeout-timer)
            (should (= emacs-jupyter-notebook--heartbeat-misses 0))
            (should-not emacs-jupyter-notebook--tunnel-dead)
            (should-not (memq timeout timer-list)))
        (cancel-timer timeout)
        (emacs-jupyter-notebook--heartbeat-cancel)))))

(ert-deftest ejn-heartbeat-setup-racing-probe-timeout-is-not-a-miss ()
  "A probe begun before setup cannot declare its busy shell unreachable."
  (with-temp-buffer
    (let ((emacs-jupyter-notebook--client 'test-client)
          (emacs-jupyter-notebook--execution-active-id nil)
          (emacs-jupyter-notebook--kernel-status nil)
          (emacs-jupyter-notebook--tunnel-dead nil)
          (emacs-jupyter-notebook--heartbeat-misses 1)
          (emacs-jupyter-notebook-heartbeat-misses-allowed 2)
          (emacs-jupyter-notebook-heartbeat-timeout 60)
          timeout lost)
      (unwind-protect
          (cl-letf (((symbol-function 'emacs-jupyter-notebook-backend-aux)
                     (lambda (&rest _) "heartbeat-request"))
                    ((symbol-function 'emacs-jupyter-notebook--tunnel-lost)
                     (lambda (&rest _) (setq lost t)))
                    ((symbol-function 'emacs-jupyter-notebook--log-append) #'ignore)
                    ((symbol-function 'display-warning) #'ignore))
            (emacs-jupyter-notebook--heartbeat-tick)
            (setq timeout emacs-jupyter-notebook--heartbeat-timeout-timer)
            (should (timerp timeout))
            (setq emacs-jupyter-notebook--execution-setup-pending t)
            ;; Model the one-shot timer being removed before its queued
            ;; callback runs, after setup has acquired the shell.
            (cancel-timer timeout)
            (apply (timer--function timeout) (timer--args timeout))
            (should-not lost)
            (should (= emacs-jupyter-notebook--heartbeat-misses 0))
            (should-not emacs-jupyter-notebook--heartbeat-inflight)
            (should-not emacs-jupyter-notebook--heartbeat-timeout-timer)
            (should-not (memq timeout timer-list)))
        (when (timerp timeout) (cancel-timer timeout))
        (emacs-jupyter-notebook--heartbeat-cancel)))))

(ert-deftest ejn-heartbeat-setup-completion-restores-idle-probing ()
  "Serial setup, including a failed step, suppresses probes until finished."
  (with-temp-buffer
    (let ((emacs-jupyter-notebook--client 'test-client)
          (emacs-jupyter-notebook--execution-active-id nil)
          (emacs-jupyter-notebook--kernel-status nil)
          (emacs-jupyter-notebook--tunnel-dead nil)
          (emacs-jupyter-notebook-enable-pickle-viewer nil)
          (emacs-jupyter-notebook-kernel-idle-timeout 0)
          (emacs-jupyter-notebook-heartbeat-timeout 60)
          (sent 0) setup-callback setup-error-callback heartbeat-callback timeout)
      (unwind-protect
          (cl-letf (((symbol-function 'emacs-jupyter-notebook--array-publisher-setup-for-client)
                     (lambda (_) '("first setup" "second setup")))
                    ((symbol-function 'emacs-jupyter-notebook-backend-execute)
                     (lambda (_client _code options callback error-callback)
                       (should (plist-get options :setup))
                       (should-not (plist-get options :ledger-id))
                       (setq setup-callback callback
                             setup-error-callback error-callback)
                       "setup-request"))
                    ((symbol-function 'emacs-jupyter-notebook-backend-aux)
                     (lambda (_client operation _payload callback &rest _)
                       (should (eq operation 'kernel-info))
                       (cl-incf sent)
                       (setq heartbeat-callback callback)
                       "heartbeat-request"))
                    ((symbol-function 'emacs-jupyter-notebook--execution-pump) #'ignore)
                    ((symbol-function 'emacs-jupyter-notebook-variables-execution-finished) #'ignore)
                    ((symbol-function 'emacs-jupyter-notebook--log-append) #'ignore)
                    ((symbol-function 'emacs-jupyter-notebook--reset-auto-reconnect-episode) #'ignore))
            (emacs-jupyter-notebook--execution-start-setup 'test-client)
            (should emacs-jupyter-notebook--execution-setup-pending)
            (emacs-jupyter-notebook--heartbeat-tick)
            (should (= sent 0))
            (funcall setup-error-callback "setup-first" "test-owned setup failure")
            (should emacs-jupyter-notebook--execution-setup-pending)
            (emacs-jupyter-notebook--heartbeat-tick)
            (should (= sent 0))
            (funcall setup-callback "setup-second" nil)
            (should-not emacs-jupyter-notebook--execution-setup-pending)
            (emacs-jupyter-notebook--heartbeat-tick)
            (should (= sent 1))
            (setq timeout emacs-jupyter-notebook--heartbeat-timeout-timer)
            (should (timerp timeout))
            (funcall heartbeat-callback "heartbeat-request" '(:alive t))
            (should-not emacs-jupyter-notebook--heartbeat-inflight)
            (should-not emacs-jupyter-notebook--heartbeat-timeout-timer)
            (should (= emacs-jupyter-notebook--heartbeat-misses 0))
            (should-not (memq timeout timer-list)))
        (when (timerp timeout) (cancel-timer timeout))
        (emacs-jupyter-notebook--heartbeat-cancel)))))

(ert-deftest ejn-heartbeat-threshold-retires-before-fallible-notifications ()
  "Presentation or recovery failure cannot keep a spent monitor polling."
  (dolist (failure '(warning log recovery))
    (with-temp-buffer
      (let ((emacs-jupyter-notebook--client 'test-client)
            (emacs-jupyter-notebook--kernel-status nil)
            (emacs-jupyter-notebook--tunnel-dead nil)
            (emacs-jupyter-notebook-heartbeat-interval 300)
            (emacs-jupyter-notebook-heartbeat-timeout 60)
            (emacs-jupyter-notebook-heartbeat-misses-allowed 2)
            (recovered 0) (sent 0) monitor timeout)
        (unwind-protect
            (cl-letf (((symbol-function 'emacs-jupyter-notebook-backend-aux)
                       (lambda (&rest _) (cl-incf sent) "heartbeat-request"))
                      ((symbol-function 'display-warning)
                       (lambda (&rest _)
                         (when (eq failure 'warning)
                           (error "Injected warning display failure"))))
                      ((symbol-function 'emacs-jupyter-notebook--log-append)
                       (lambda (&rest _)
                         (when (eq failure 'log)
                           (error "Injected log display failure"))))
                      ((symbol-function 'emacs-jupyter-notebook--tunnel-lost)
                       (lambda (&rest _)
                         (cl-incf recovered)
                         (when (eq failure 'recovery)
                           (error "Injected recovery callback failure"))
                         (setq emacs-jupyter-notebook--tunnel-dead t))))
              (emacs-jupyter-notebook--heartbeat-start)
              (setq monitor emacs-jupyter-notebook--heartbeat-timer)
              ;; The event loop catches timer errors and would keep invoking
              ;; a repeating timer unless retirement happened first.
              (dotimes (_ 15)
                (condition-case nil
                    (emacs-jupyter-notebook--heartbeat-on-miss)
                  (error nil)))
              (should (= recovered 1))
              (should emacs-jupyter-notebook--tunnel-dead)
              (should-not emacs-jupyter-notebook--heartbeat-timer)
              (should-not emacs-jupyter-notebook--heartbeat-timeout-timer)
              (should-not (memq monitor timer-list))
              (emacs-jupyter-notebook--heartbeat-tick)
              (should (= sent 0))
              ;; Successful reconnect explicitly starts the next monitor.
              (setq emacs-jupyter-notebook--tunnel-dead nil)
              (emacs-jupyter-notebook--heartbeat-start)
              (emacs-jupyter-notebook--heartbeat-tick)
              (setq timeout emacs-jupyter-notebook--heartbeat-timeout-timer)
              (should (= sent 1))
              (should (timerp timeout)))
          (when (timerp monitor) (cancel-timer monitor))
          (when (timerp timeout) (cancel-timer timeout))
          (emacs-jupyter-notebook--heartbeat-cancel))))))

(provide 'emacs-jupyter-notebook-heartbeat-setup-tests)
;;; emacs-jupyter-notebook-heartbeat-setup-tests.el ends here
