;;; emacs-jupyter-notebook-ux-integration-tests.el --- UX ownership checks -*- lexical-binding: t; -*-

(require 'ert)
(require 'emacs-jupyter-notebook)

(ert-deftest ejn-ux-inspection-watch-precedes-dispatch-and-source-is-clean ()
  (with-temp-buffer
    (insert "# %% Data\nimage = something()\n")
    (let ((before (buffer-string))
          (emacs-jupyter-notebook-inspect--watches nil)
          (handle (list :id 17 :panel 'fake :generation 4 :cell-key nil))
          record)
      (cl-letf (((symbol-function 'ejn-panel-ensure) (lambda (_) 'fake))
                ((symbol-function 'ejn-panel-start-entry)
                 (lambda (_panel _key _code title)
                   (should (equal title "Inspect image")) handle))
                ((symbol-function 'ejn-panel-set-entry-status) #'ignore)
                ((symbol-function 'ejn-panel-reveal-entry) #'ignore)
                ((symbol-function 'emacs-jupyter-notebook-panel--display) #'ignore)
                ((symbol-function 'emacs-jupyter-notebook--execution-pump)
                 (lambda ()
                   (setq record (emacs-jupyter-notebook--execution-record
                                 (car emacs-jupyter-notebook--execution-queue)))
                   (should (equal (cdr (assq (current-buffer)
                                            emacs-jupyter-notebook-inspect--watches)) handle)))))
        (set-buffer-modified-p nil)
        (emacs-jupyter-notebook-inspect-evaluate "ejn.view_variable(\"image\")" "Inspect image")
        (should (plist-get record :inspection))
        (should (equal before (buffer-string)))
        (should-not (buffer-modified-p))
        (let ((wire (emacs-jupyter-notebook-helper-backend--payload-object
                     'execute (list :code (plist-get record :code)
                                    :options (list :inspection t)))))
          (should (eq (gethash "store_history" wire) :false)))))))

(ert-deftest ejn-ux-normal-execute-retains-default-history-contract ()
  (let ((wire (emacs-jupyter-notebook-helper-backend--payload-object
               'execute '(:code "x = 1" :options (:ledger-id 2)))))
    (should (= (hash-table-count wire) 1))
    (should (equal (gethash "code" wire) "x = 1"))))

(ert-deftest ejn-ux-automatic-follow-cannot-replace-explicit-pending-inspection ()
  (let* ((explicit (list :focus t :lease 'selected-publication))
         (state (ejn-inspection-create :pending explicit))
         (emacs-jupyter-notebook-inspect--state state)
         (releases 0))
    (emacs-jupyter-notebook-inspect-publication
     (list :workspace "automatic" :release (lambda () (cl-incf releases))) t)
    (should (eq (ejn-inspection-pending state) explicit))
    (should (= releases 1))))

(ert-deftest ejn-ux-closed-viewer-ack-releases-lease-and-retires-only-its-follow ()
  (let* ((releases 0)
         (state (ejn-inspection-create :ready t))
         (emacs-jupyter-notebook-inspect--state state)
         (closed-follow (list :state state :workspace "closed" :timer nil))
         (other-follow (list :state state :workspace "other" :timer nil))
         (emacs-jupyter-notebook-inspect--follows (list closed-follow other-follow)))
    (setf (ejn-inspection-active state)
          (list :id "open-1" :lease (list :workspace "closed"
                                         :release (lambda () (cl-incf releases)))))
    (cl-letf (((symbol-function 'emacs-jupyter-notebook-inspect--report) #'ignore))
      (emacs-jupyter-notebook-inspect--response
       state (emacs-jupyter-notebook-inspect--object
              "v" 1 "id" "open-1" "ok" t "result"
              (emacs-jupyter-notebook-inspect--object "state" "visible" "closed" t))))
    (should (= releases 1))
    (should-not (ejn-inspection-active state))
    (should (equal emacs-jupyter-notebook-inspect--follows (list other-follow)))))

(ert-deftest ejn-ux-follow-coalesces-exact-workspace-without-focus ()
  (with-temp-buffer
    (let* ((source (current-buffer))
           (panel (generate-new-buffer " *ejn-ux-panel*"))
           (state (ejn-inspection-create))
           (emacs-jupyter-notebook-inspect--state state)
           (emacs-jupyter-notebook-inspect--follows nil)
           (emacs-jupyter-notebook-inspect--watches nil)
           (handle (list :panel panel :id 3 :generation 1 :cell-key 'cell-a))
           (lease (list :source-buffer source :cell-key 'cell-a :workspace "ws/a"
                        :generation 1 :entry-handle handle :release #'ignore))
           (timer (timer-create)) callback acquired opened (scheduled 0))
      (unwind-protect
          (progn
            (with-current-buffer panel
              (setq-local emacs-jupyter-notebook-panel--source-buffer source))
            (emacs-jupyter-notebook-inspect--remember-follow lease state)
            (cl-letf (((symbol-function 'run-at-time)
                       (lambda (_time _repeat fn &rest _) (cl-incf scheduled)
                         (setq callback fn) timer))
                      ((symbol-function 'ejn-panel-entry-snapshot)
                       (lambda (_handle)
                         '(:outputs ((array :output-id 1 :workspace "ws/a")
                                     (array :output-id 2 :workspace "ws/a")
                                     (array :output-id 3 :workspace "ws/b")))))
                      ((symbol-function 'ejn-panel-acquire-array)
                       (lambda (h id) (setq acquired (list h id)) lease))
                      ((symbol-function 'emacs-jupyter-notebook-inspect-publication)
                       (lambda (value no-focus) (setq opened (list value no-focus)))))
              (emacs-jupyter-notebook-inspect--published handle 1)
              (emacs-jupyter-notebook-inspect--published handle 2)
              (emacs-jupyter-notebook-inspect--published handle 3)
              (should (= scheduled 1))
              (funcall callback)
              (should (equal acquired (list handle 2)))
              (should (equal opened (list lease t)))
              (setq opened nil)
              (emacs-jupyter-notebook-inspect--published handle 1)
              (emacs-jupyter-notebook-inspect--owner-killed)
              (should-not emacs-jupyter-notebook-inspect--follows)
              (funcall callback)
              (should-not opened)))
        (cancel-timer timer)
        (kill-buffer panel)))))

(ert-deftest ejn-ux-inspect-dispatches-source-identifier-without-evaluation ()
  (with-temp-buffer
    (python-mode)
    (insert "image")
    (let ((emacs-jupyter-notebook-mode t) inspected)
      (cl-letf (((symbol-function 'emacs-jupyter-notebook-inspect-variable)
                 (lambda () (interactive) (setq inspected t)))
                ((symbol-function 'emacs-jupyter-notebook-send-cell)
                 (lambda () (ert-fail "Inspect must never evaluate source"))))
        (emacs-jupyter-notebook-inspect)
        (should inspected)))))

(ert-deftest ejn-ux-context-menu-shows-shortcuts-and-invokes-selected-action ()
  (with-temp-buffer
    (let ((emacs-jupyter-notebook-mode t) selected)
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (_prompt choices &rest _)
                   (car (cl-find-if (lambda (entry) (eq (cdr entry) 'emacs-jupyter-notebook-list-variables)) choices))))
                ((symbol-function 'emacs-jupyter-notebook-list-variables)
                 (lambda () (interactive) (setq selected t))))
        (emacs-jupyter-notebook-actions)
        (should selected)))))

(ert-deftest ejn-ux-mixed-output-inspect-honors-selected-segment ()
  (with-temp-buffer
    (setq major-mode 'emacs-jupyter-notebook-panel-mode)
    (insert (propertize "array card" 'emacs-jupyter-notebook-segment-index 1))
    (goto-char (point-min))
    (let (opened)
      (cl-letf (((symbol-function 'emacs-jupyter-notebook-panel--entry-id-at-point) (lambda () 1))
                ((symbol-function 'emacs-jupyter-notebook-panel--entry)
                 (lambda (&rest _) '(:outputs ((image . png) (array . numerical)))))
                ((symbol-function 'emacs-jupyter-notebook-panel--image-at-point) (lambda () 'png))
                ((symbol-function 'emacs-jupyter-notebook-inspect-images) (lambda () (setq opened 'array)))
                ((symbol-function 'emacs-jupyter-notebook-panel-open-image-externally) (lambda () (setq opened 'image))))
        (emacs-jupyter-notebook-inspect)
        (should (eq opened 'array))
        (put-text-property (point-min) (point-max) 'emacs-jupyter-notebook-segment-index 0)
        (emacs-jupyter-notebook-inspect)
        (should (eq opened 'image))))))

(provide 'emacs-jupyter-notebook-ux-integration-tests)
