;;; emacs-jupyter-notebook-helper-protocol-tests.el --- ET1 tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'json)
(require 'emacs-jupyter-notebook-helper-protocol)

(defconst ejn-et1-test-fixture
  (expand-file-name "tests/fixtures/helper-protocol-v1.json"
                    (file-name-directory (directory-file-name
                                          (file-name-directory
                                           (file-truename load-file-name))))))

(defun ejn-et1-json (object)
  (encode-coding-string
   (json-serialize object :null-object :null :false-object :false)
   'utf-8 t))

(defun ejn-et1-get (object key)
  (gethash key object))

(defun ejn-et1-hex (hex)
  (let ((bytes (make-string (/ (length hex) 2) 0)) (index 0))
    (while (< index (length bytes))
      (aset bytes index (string-to-number (substring hex (* index 2) (+ (* index 2) 2)) 16))
      (setq index (1+ index)))
    bytes))

(defun ejn-et1-wire (object)
  (let ((payload (ejn-et1-json object)))
    (concat (unibyte-string (logand (ash (length payload) -24) 255)
                            (logand (ash (length payload) -16) 255)
                            (logand (ash (length payload) -8) 255)
                            (logand (length payload) 255))
            payload)))

(ert-deftest ejn-et1-code-byte-limit-is-the-shared-protocol-contract ()
  "The Elisp protocol owns the same fixed execute payload ceiling as EI3."
  (should (= ejn-helper-protocol-max-code-bytes 524288)))

(defun ejn-et1-recipe-object (vector)
  (let* ((template (copy-hash-table (ejn-et1-get vector "template")))
         (key (if (equal (ejn-et1-get template "kind") "response")
                  "result" "params"))
         (container (copy-hash-table (ejn-et1-get template key)))
         (field (ejn-et1-get vector "field"))
         (empty (copy-hash-table template)))
    (puthash field "" container)
    (puthash key container empty)
    (puthash field (make-string (- (ejn-et1-get vector "target_frame_length") 4
                                   (length (ejn-et1-json empty))) ?a)
             container)
    (puthash key container template)
    template))

(defun ejn-et1-vector-object (vector)
  (if (member (ejn-et1-get vector "kind") '("recipe" "recipe-error"))
      (ejn-et1-recipe-object vector)
    (ejn-et1-get vector "object")))

(defun ejn-et1-chunks (wire)
  (let ((result nil) (index 0) (length (length wire)))
    (while (< index length)
      (let ((width (min (- length index) (1+ (mod (+ index 7) 13)))))
        (push (substring wire index (+ index width)) result)
        (setq index (+ index width))))
    (nreverse result)))

(defun ejn-et1-equal (left right)
  "Compare fixture JSON values recursively, including hash tables."
  (cond
   ((and (hash-table-p left) (hash-table-p right))
    (and (= (hash-table-count left) (hash-table-count right))
         (let ((same t))
           (maphash (lambda (key value)
                      (unless (and (gethash key right :missing)
                                   (ejn-et1-equal value (gethash key right)))
                        (setq same nil))) left)
           same)))
   ((and (vectorp left) (vectorp right))
    (and (= (length left) (length right))
         (cl-loop for value across left
                  for other across right
                  always (ejn-et1-equal value other))))
   ((and (listp left) (listp right))
    (and (= (length left) (length right))
         (cl-every #'identity (cl-mapcar #'ejn-et1-equal left right))))
   (t (equal left right))))

(defun ejn-et1-should-error-code (code thunk)
  "Assert that THUNK signals the protocol CODE."
  (let ((caught nil))
    (condition-case err
        (funcall thunk)
      (ejn-helper-protocol-error (setq caught err)))
    (should caught)
    (should (eq (nth 1 caught) code))))

(ert-deftest ejn-et1-fixture-all-vectors ()
  (let* ((fixture (json-parse-string (with-temp-buffer
                                       (insert-file-contents ejn-et1-test-fixture)
                                       (buffer-string))
                                     :object-type 'hash-table
                                     :array-type 'array
                                     :null-object :null :false-object :false))
         (vectors (append (ejn-et1-get fixture "vectors") nil))
         (valid-count 0)
         (small-wires nil)
         (small-objects nil)
         (kind-counts (make-hash-table :test #'equal)))
    (dolist (vector vectors)
      (let ((kind (ejn-et1-get vector "kind")))
        (puthash kind (1+ (gethash kind kind-counts 0)) kind-counts)
        (cond
         ((equal kind "raw-error")
          (let ((wire (ejn-et1-hex (ejn-et1-get vector "raw_hex")))
                (code (ejn-et1-get (ejn-et1-get vector "error") "code")))
            (if (ejn-et1-get vector "outcome")
                (let ((decoder (ejn-helper-protocol-make-decoder 1048576)))
                  (ejn-helper-protocol-decoder-feed decoder wire)
                  (should-error (ejn-helper-protocol-decoder-expire-partial decoder)))
              (if (equal code "protocol-error")
                (should-error (ejn-helper-protocol-decoder-feed
                               (ejn-helper-protocol-make-decoder
                                (ejn-et1-get (ejn-et1-get fixture "limits")
                                             "max_to_helper_frame")) wire))
              (should (hash-table-p
                       (car (ejn-helper-protocol-decoder-feed
                             (ejn-helper-protocol-make-decoder 1048576) wire))))))))
         ((member kind '("frame" "recipe" "recipe-error"))
          (let* ((object (ejn-et1-vector-object vector))
                 (wire (ejn-et1-wire object))
                 (direction (ejn-et1-get vector "direction"))
                 (limits (ejn-et1-get fixture "limits"))
                 (ceiling (cond ((equal direction "response") (ejn-et1-get limits "max_response_frame"))
                                ((equal direction "to-helper") (ejn-et1-get limits "max_to_helper_frame"))
                                (t (ejn-et1-get limits "max_to_emacs_frame")))))
            (when (ejn-et1-get vector "declared_payload_length")
              (should (= (ejn-et1-get vector "declared_payload_length") (- (length wire) 4)))
              (should (equal (ejn-et1-get vector "prefix_hex")
                             (substring (mapconcat (lambda (byte) (format "%02x" byte)) wire "") 0 8))))
            (when (ejn-et1-get vector "expected_payload_length")
              (should (= (ejn-et1-get vector "expected_payload_length") (- (length wire) 4)))
              (should (equal (ejn-et1-get vector "expected_prefix_hex")
                             (substring (mapconcat (lambda (byte) (format "%02x" byte)) wire "") 0 8))))
            (dolist (split (append (ejn-et1-get vector "split_points") nil))
              (let ((decoder (ejn-helper-protocol-make-decoder ceiling))
                    (decoded nil))
                (setq decoded (append decoded (ejn-helper-protocol-decoder-feed decoder (substring wire 0 split))))
                (setq decoded (append decoded (ejn-helper-protocol-decoder-feed decoder (substring wire split))))
                (should (= (length decoded) 1))
                (should (ejn-et1-equal (car decoded) object))))
            (if (equal kind "recipe-error")
                (progn
                  (should-error (ejn-helper-protocol-encode object ceiling))
                  (should-error (ejn-helper-protocol-decoder-feed
                                 (ejn-helper-protocol-make-decoder ceiling) (substring wire 0 4))))
              (cl-incf valid-count)
              (when (and (equal kind "frame") (<= (length wire) 256))
                (push wire small-wires)
                (push object small-objects)
                (dotimes (split (1+ (length wire)))
                  (let ((decoder (ejn-helper-protocol-make-decoder ceiling))
                        (decoded nil))
                    (setq decoded (append decoded (ejn-helper-protocol-decoder-feed decoder (substring wire 0 split))))
                    (setq decoded (append decoded (ejn-helper-protocol-decoder-feed decoder (substring wire split))))
                    (should (= (length decoded) 1))
                    (should (ejn-et1-equal (car decoded) object)))))
              (let ((decoder (ejn-helper-protocol-make-decoder ceiling))
                    (decoded nil))
                (dolist (chunk (ejn-et1-chunks wire))
                  (setq decoded (append decoded
                                        (ejn-helper-protocol-decoder-feed decoder chunk))))
                (should (= (length decoded) 1))
                (should (ejn-et1-equal (car decoded) object)))))))))
    (setq small-wires (nreverse small-wires)
          small-objects (nreverse small-objects))
    (let ((decoded (ejn-helper-protocol-decoder-feed
                    (ejn-helper-protocol-make-decoder 262144)
                    (apply #'concat (cl-subseq small-wires 0 3)))))
      (should (= (length decoded) 3))
      (should (cl-loop for actual in decoded
                       for expected in (cl-subseq small-objects 0 3)
                       always (ejn-et1-equal actual expected))))
    (should (= (length vectors) 53))
    (should (= (gethash "frame" kind-counts) 39))
    (should (= (gethash "recipe" kind-counts) 3))
    (should (= (gethash "recipe-error" kind-counts) 3))
    (should (= (gethash "raw-error" kind-counts) 8))
    (should (= valid-count 42))))

(ert-deftest ejn-et1-boundaries-and-state ()
  (let ((decoder (ejn-helper-protocol-make-decoder 100)))
    (ejn-helper-protocol-decoder-feed decoder (unibyte-string 0 0 0 3))
    (should (ejn-helper-protocol-decoder-partial-p decoder))
    (should-error (ejn-helper-protocol-decoder-expire-partial decoder))
    (should (ejn-helper-protocol-decoder-failed decoder)))
  (should-error (ejn-helper-protocol-encode (make-hash-table) 4)))

(ert-deftest ejn-et1-immutability-and-unibyte ()
  (let ((object (make-hash-table :test #'equal)))
    (puthash "v" 1 object)
    (puthash "kind" "request" object)
    (let ((before (copy-hash-table object)) (wire (ejn-helper-protocol-encode object 100)))
      (should (ejn-et1-equal object before))
      (should-not (multibyte-string-p wire))))
  (should-error (ejn-helper-protocol-decoder-feed
                 (ejn-helper-protocol-make-decoder 100) "text")))

(ert-deftest ejn-et1-nonascii-raw-bytes ()
  (let* ((payload (encode-coding-string "{\"text\":\"π\"}" 'utf-8 t))
         (wire (concat (unibyte-string 0 0 0 (length payload)) payload))
         (decoder (ejn-helper-protocol-make-decoder 100)))
    (ejn-helper-protocol-decoder-feed decoder (substring wire 0 5))
    (should-not (multibyte-string-p (ejn-helper-protocol-decoder-unconsumed-bytes decoder)))
    (should (equal (ejn-helper-protocol-decoder-unconsumed-bytes decoder)
                   (substring wire 4 5)))
    (should (hash-table-p (car (ejn-helper-protocol-decoder-feed decoder (substring wire 5)))))))

(ert-deftest ejn-et1-recipe-ceilings ()
  (let* ((fixture (json-parse-string
                   (with-temp-buffer
                     (insert-file-contents ejn-et1-test-fixture)
                     (buffer-string))
                   :object-type 'hash-table :array-type 'array
                   :null-object :null :false-object :false))
         (limits (ejn-et1-get fixture "limits")))
    (dolist (vector (append (ejn-et1-get fixture "vectors") nil))
      (when (equal (ejn-et1-get vector "kind") "recipe")
        (let* ((object (ejn-et1-recipe-object vector))
               (direction (ejn-et1-get vector "direction"))
               (ceiling (cond
                         ((equal direction "response")
                          (ejn-et1-get limits "max_response_frame"))
                         ((equal direction "to-helper")
                          (ejn-et1-get limits "max_to_helper_frame"))
                         (t (ejn-et1-get limits "max_to_emacs_frame")))))
          (should (= (length (ejn-helper-protocol-encode object ceiling))
                     ceiling))
          (let* ((oversize (copy-hash-table object))
                 (key (if (equal (ejn-et1-get oversize "kind") "response")
                          "result" "params"))
                 (container (copy-hash-table (ejn-et1-get oversize key)))
                 (field (ejn-et1-get vector "field")))
            (puthash field (concat (gethash field container) "a") container)
            (puthash key container oversize)
            (ejn-et1-should-error-code
             'frame-too-large
             (lambda () (ejn-helper-protocol-encode oversize ceiling)))
            (ejn-et1-should-error-code
             'frame-too-large
             (lambda ()
               (ejn-helper-protocol-decoder-feed
                (ejn-helper-protocol-make-decoder ceiling)
                (substring (ejn-et1-wire oversize) 0 4))))))))))

(ert-deftest ejn-et1-raw-json-errors-and-empty-object ()
  (dolist (payload (list "x" "[]" "\"x\"" "1" "null" "{\"x\":NaN}" "{\"x\":Infinity}"))
    (let* ((bytes (encode-coding-string payload 'utf-8 t))
           (wire (concat (unibyte-string 0 0 0 (length bytes)) bytes))
           (decoder (ejn-helper-protocol-make-decoder 1024)))
      (ejn-et1-should-error-code
       'protocol-error
       (lambda () (ejn-helper-protocol-decoder-feed decoder wire)))))
  (let* ((wire (concat (unibyte-string 0 0 0 2) "{}"))
         (object (car (ejn-helper-protocol-decoder-feed (ejn-helper-protocol-make-decoder 100) wire))))
    (should (hash-table-p object))
    (should (= (hash-table-count object) 0))))

(ert-deftest ejn-et1-accumulator-expiry-and-closure ()
  (let ((decoder (ejn-helper-protocol-make-decoder 100 100)))
    (should-error (ejn-helper-protocol-decoder-feed decoder (make-string 101 0)))
    (should (ejn-helper-protocol-decoder-failed decoder))
    (should (= (ejn-helper-protocol-decoder-buffered-bytes decoder) 0))
    (should-not (ejn-helper-protocol-decoder-chunks decoder))
    (should-not (ejn-helper-protocol-decoder-tail decoder))
    (should-not (ejn-helper-protocol-decoder-need decoder))
    (should-not (ejn-helper-protocol-decoder-partial-p decoder))
    (should-error (ejn-helper-protocol-decoder-feed decoder "")))
  (dolist (bytes (list (unibyte-string 0 0) (unibyte-string 0 0 0 4)))
    (let ((decoder (ejn-helper-protocol-make-decoder 100)))
      (ejn-helper-protocol-decoder-feed decoder bytes)
      (should (ejn-helper-protocol-decoder-partial-p decoder))
      (should-error (ejn-helper-protocol-decoder-expire-partial decoder))
      (should (= (ejn-helper-protocol-decoder-buffered-bytes decoder) 0)))))

(ert-deftest ejn-et1-nested-immutability-and-unibyte ()
  (let ((object (make-hash-table :test #'equal))
        (nested (make-hash-table :test #'equal)))
    (puthash "items" (vector "alpha" :null :false) nested)
    (puthash "unicode" "π" object)
    (puthash "null" :null object)
    (puthash "false" :false object)
    (puthash "nested" nested object)
    (let ((before (ejn-et1-json object)) (wire (ejn-helper-protocol-encode object 1024)))
      (should (string= before (ejn-et1-json object)))
      (should-not (multibyte-string-p wire))))
  (let ((decoder (ejn-helper-protocol-make-decoder 100)))
    (should-error (ejn-helper-protocol-decoder-feed decoder "π"))
    (should (= (ejn-helper-protocol-decoder-buffered-bytes decoder) 0))))

(ert-deftest ejn-et1-large-byte-feed-take-count ()
  (let* ((object (make-hash-table :test #'equal)) (code (make-string 10000 ?a)))
    (puthash "code" code object)
    (let* ((wire (ejn-helper-protocol-encode object 20000))
           (decoder (ejn-helper-protocol-make-decoder 20000))
           (calls 0) (bytes 0)
           (advice (lambda (original target count)
                     (cl-incf calls)
                     (cl-incf bytes count)
                     (funcall original target count))))
      (advice-add 'ejn-helper-protocol--take :around advice)
      (unwind-protect
          (let (result)
            (dotimes (index (length wire))
              (setq result (append result (ejn-helper-protocol-decoder-feed decoder (substring wire index (1+ index))))))
            (should (= (length result) 1))
            (should (equal (gethash "code" (car result)) code))
            (should (= calls 2))
            (should (= bytes (length wire))))
        (advice-remove 'ejn-helper-protocol--take advice)))))

(provide 'emacs-jupyter-notebook-helper-protocol-tests)
;;; emacs-jupyter-notebook-helper-protocol-tests.el ends here
